config/routes.rb
Rails.application.routes.draw do

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  namespace 'admin' do
    resources :students
    resources :projects
  end

  resources :students, only: [:index, :edit, :update, :show] do
     resources :my_projects, only: [:create, :new, :destroy, :show]
  end
  resources :projects, only: [:index, :show]

  root to: 'students#index'
  get '/analytics', to: "analytics#index"
end

app/models/student.rb
class Student < ActiveRecord::Base
  # attr_accessor :avatar_file_name
  has_secure_password

  has_many :my_projects
  has_many :projects, through: :my_projects
  has_many :partnerships, through: :my_projects

  validates :name, presence: true
  validates :cohort, presence: true
  validates :username, presence: true
  validates :password_digest, presence: true

  has_attached_file :avatar, :path => ":rails_root/public/system/:attachment/:id/:style/:filename",
  :url => "/system/:attachment/:id/:style/:filename",
  styles: {
    favicon: '16x16>',
    square: '200x200#',
    medium: '300x300>'
  },
  :s3_credentials => {
    :bucket => ENV['S3_BUCKET_NAME'],
    :access_key_id => ENV['AWS_ACCESS_KEY_ID'],
    :secret_access_key => ENV['AWS_SECRET_ACCESS_KEY']
  }

  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  enum role: %w(default admin)


  def partners(my_project)
    all_connected = MyProject.where(partnership_id: my_project.partnership_id)
    all_connected.map do | my_project |
      my_project.student
    end
  end

  def paired
    my_projects.map do |project|
      MyProject.where(partnership_id: project.partnership_id).map do |partner_project|
        partner_project.student.name
      end
    end.flatten.uniq.delete_if { |name| name == self.name }
  end

  def unpaired
    Student.all.select do |student|
      !paired.include?(student.name)
    end.map do |non_pair|
      non_pair.name
    end.delete_if { |name| name == self.name }
  end
end

app/controllers/admin/students_controller.rb
class Admin::StudentsController < Admin::BaseController
  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      if !@student.email.empty?
        StudentMailer.welcome_email(@student).deliver_now
      end
      redirect_to admin_students_path
    else
      render :new
    end
  end

  def index
    @students = Student.all
  end

  def show
    @student = Student.find(params[:id])
  end

  def destroy
    @student = Student.find(params[:id])
    @student.destroy
    redirect_to admin_students_path
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])
    @student.update(student_params)
    redirect_to admin_students_path
  end

  private

  def student_params
    params.require(:student).permit(:username, :password, :name, :cohort, :email)
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :find_student, only: [:show, :edit, :update]

  def show
  end

  def index
    @students = Student.all
  end

  def edit
    render file: 'public/404' if params[:id].to_i != current_user.id
  end

  def update
    @student.update(student_params)
    if @student.save
      flash.notice = "Successfully updated your profile"
      redirect_to student_path(@student)
    else
      flash.alert = "#{@student.errors.full_messages.join(", ")}"
      render :new
    end
  end

  private

  def student_params
    params.require(:student).permit(:password, :cohort, :avatar)
  end

  def find_student
    @student = Student.find(params[:id])
  end

end

app/views/students/edit.html.erb
<%= form_for @student do |f| %>
<%= f.label :password %>
<%= f.password_field :password %>
<%= f.label :cohort %>
<%= f.text_field :cohort %>
<%= f.label :avatar %>
<%= f.file_field :avatar %>
<%= f.submit %>
<% end %>

app/views/students/index.html.erb
<h1>All Students</h1>
<table class="table">
  <tr>
    <th>Name</th>
    <th>Username</th>
    <th>Cohort</th>
  </tr>
<% @students.each do |student| %>
<tr>
  <td><%= link_to student.name, student_path(student)%></td>
  <td> <%= student.username %></td>
  <td> <%= student.cohort %></td>
</tr
<% end %>
</table>

app/views/students/show.html.erb
  <h1>Your Profile</h1>

  <%= image_tag @student.avatar.url(:medium) %>
 <p>
   Name: <%= @student.name %>
 </p>
 <p>
   Cohort: <%= @student.cohort %>
 </p>

<table class="table">
  <tr>
    <th>Project</th>
    <th>Module</th>
    <th></th>
  </tr>
  <% @student.projects.each do |project| %>
  <tr>
    <td><%= link_to project.name, student_my_project_path(@student, @student.my_projects.find_by(project_id: project.id).id) %></td>
    <td><%= project.module %></td>
    <td><%= link_to "Delete", student_my_project_path(@student, project), method: :delete %></td>
  </tr>
  <% end %>
</table>

<div class="paired">
  <h3>Students You Have Worked With</h3>
  <ul>
    <% @student.paired.each do |pair| %>
    <li><%= pair %></li>
    <% end %>
  </ul>
</div>

<div class="unpaired">
  <h3>Students You Haven't Worked With</h3>
  <ul>
    <% @student.unpaired.each do |pair| %>
    <li><%= pair %></li>
    <% end %>
  </ul>
</div>

<% if @student.id == current_user.id %>
  <%= link_to "Edit Profile", edit_student_path(@student) %>
    <%= link_to "Add a Project to Your List", new_student_my_project_path(@student) %>
<% end %>