config/routes.rb
Rails.application.routes.draw do

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  namespace 'admin' do
    resources :students
    resources :projects
  end

  resources :students, only: [:index, :edit, :update, :show] do
     resources :my_projects, only: [:create, :new, :destroy, :show]
  end
  resources :projects, only: [:index, :show]

  root to: 'students#index'
  get '/analytics', to: "analytics#index"
end

app/models/student.rb
class Student < ActiveRecord::Base
  # attr_accessor :avatar_file_name
  has_secure_password

  has_many :my_projects
  has_many :projects, through: :my_projects
  has_many :partnerships, through: :my_projects

  validates :name, presence: true
  validates :cohort, presence: true
  validates :username, presence: true
  validates :password_digest, presence: true

  has_attached_file :avatar, :path => ":rails_root/public/system/:attachment/:id/:style/:filename",
  :url => "/system/:attachment/:id/:style/:filename",
  styles: {
    favicon: '16x16>',
    square: '200x200#',
    medium: '300x300>'
  },
  :s3_credentials => {
    :bucket => ENV['S3_BUCKET_NAME'],
    :access_key_id => ENV['AWS_ACCESS_KEY_ID'],
    :secret_access_key => ENV['AWS_SECRET_ACCESS_KEY']
  }

  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  enum role: %w(default admin)


  def partners(my_project)
    all_connected = MyProject.where(partnership_id: my_project.partnership_id)
    all_connected.map do | my_project |
      my_project.student
    end
  end

  def paired
    my_projects.map do |project|
      MyProject.where(partnership_id: project.partnership_id).map do |partner_project|
        partner_project.student.name
      end
    end.flatten.uniq.delete_if { |name| name == self.name }
  end

  def unpaired
    Student.all.select do |student|
      !paired.include?(student.name)
    end.map do |non_pair|
      non_pair.name
    end.delete_if { |name| name == self.name }
  end
end

app/controllers/admin/students_controller.rb
class Admin::StudentsController < Admin::BaseController
  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      if !@student.email.empty?
        StudentMailer.welcome_email(@student).deliver_now
      end
      redirect_to admin_students_path
    else
      render :new
    end
  end

  def index
    @students = Student.all
  end

  def show
    @student = Student.find(params[:id])
  end

  def destroy
    @student = Student.find(params[:id])
    @student.destroy
    redirect_to admin_students_path
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])
    @student.update(student_params)
    redirect_to admin_students_path
  end

  private

  def student_params
    params.require(:student).permit(:username, :password, :name, :cohort, :email)
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :find_student, only: [:show, :edit, :update]

  def show
  end

  def index
    @students = Student.all
  end

  def edit
    render file: 'public/404' if params[:id].to_i != current_user.id
  end

  def update
    @student.update(student_params)
    if @student.save
      flash.notice = "Successfully updated your profile"
      redirect_to student_path(@student)
    else
      flash.alert = "#{@student.errors.full_messages.join(", ")}"
      render :new
    end
  end

  private

  def student_params
    params.require(:student).permit(:password, :cohort, :avatar)
  end

  def find_student
    @student = Student.find(params[:id])
  end

end

app/views/admin/students/edit.html.erb
<%= form_for @student, url: admin_student_path do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :cohort %>
  <%= f.text_field :cohort %>

  <%= f.submit %>
<% end %>

app/views/admin/students/index.html.erb
<table class="table">
  <tr>
    <th>Name</th>
    <th>Username</th>
    <th>Cohort</th>
  </tr>
  <% @students.each do |student|%>
  <tr>
    <th><%= link_to student.name, student %></th>
    <th><%= student.username %></th>
    <th><%= student.cohort %></th>
  </tr>
  <% end %>
</table>

<%= link_to "Add a new student", new_admin_student_path %>

app/views/admin/students/new.html.erb
<%= form_for @student, url: admin_students_path do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :cohort %>
  <%= f.text_field :cohort %>
  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.submit %>

<% end %>

app/views/admin/students/show.html.erb
<h1>Welcome, <%= @student.name %></h1>


<%= link_to "Edit", edit_admin_student_path(@student) %>
<%= link_to "Delete", admin_student_path(@student), method: :delete %>