config/routes.rb
Rails.application.routes.draw do

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  namespace 'admin' do
    resources :students
    resources :projects
  end

  resources :students, only: [:index, :edit, :update, :show] do
     resources :my_projects, only: [:create, :new, :destroy, :show]
  end
  resources :projects, only: [:index, :show]

  root to: 'students#index'
  get '/analytics', to: "analytics#index"
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :my_projects
  has_many :students, through: :my_projects
  has_many :partnerships, through: :my_projects

  validates :name, presence: true
  validates :module, presence: true
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::BaseController
  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to admin_projects_path
    else
      render :new
    end
  end

  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to admin_projects_path
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    @project.update(project_params)
    redirect_to admin_projects_path
  end

  private

  def project_params
    params.require(:project).permit(:name, :module)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.all
  end

end

app/views/admin/projects/edit.html.erb
<%= form_for @project, url: admin_project_path do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :module %>
<%= f.text_field :module %>
<%= f.submit %>
<% end %>

app/views/admin/projects/index.html.erb
<table class="table">
  <tr>
    <th> Name </th>
    <th> Module </th>
  </tr>
  <% @projects.each do |project| %>
    <tr>
      <td><%= link_to project.name, admin_project_path(project) %></td>
      <td><%= project.module %></td>
      <td><%= link_to "Remove Project", admin_project_path(project), method: :delete %>
    </tr>
  <% end %>
</table>

<%= link_to "Add a new project", new_admin_project_path %>

app/views/admin/projects/new.html.erb
<%= form_for @project, url: admin_projects_path do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :module %>
<%= f.text_field :module %>
<%= f.submit %>
<% end %>

app/views/admin/projects/show.html.erb
<%= link_to "Edit", edit_admin_project_path(@project) %>
<%= link_to "Delete", admin_project_path(@project), method: :delete %>