config/routes.rb
Rails.application.routes.draw do

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  namespace 'admin' do
    resources :students
    resources :projects
  end

  resources :students, only: [:index, :edit, :update, :show] do
     resources :my_projects, only: [:create, :new, :destroy, :show]
  end
  resources :projects, only: [:index, :show]

  root to: 'students#index'
  get '/analytics', to: "analytics#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TuringPartnerships</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="col-md-12 navbar navbar-default banner">
      <div class="navbar-header">
        <h1 class="navbar-brand logo" id="greeting">Turing Partnerships</h1>
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
            <li id="welcome">Welcome, <%= current_user.name %></li>
            <li><%= link_to "Log Out", logout_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Log In", login_path %></li>
          <% end %>
          <li><%= link_to "All Students", students_path %></li>
          <li><%= link_to "All Projects", projects_path %></li>
          <li><%= link_to "Analytics", analytics_path  %></li>
        </ul>
      </div>
    </div>
      <div class="container">
        <p class="flash">
          <% flash.each do | type, msg | %>
            <%= content_tag :div, msg, class: "flash_#{type}" %>
        <% end %>
        </p>
        <%= yield %>
    </div>
</div>

</body>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</html>